apiVersion: v2
name: cf2otel
description: Poll Cloudflare APIs and export logs, metrics and traces over OTLP.
type: application
version: 0.7.0
appVersion: 0.7.0
kubeVersion: '>=1.29.0-0'
home: https://github.com/rknightion/cf2otel
sources:
  - https://github.com/rknightion/cf2otel
keywords:
  - cloudflare
  - otel
  - otlp
maintainers:
  - name: rknightion
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
