// Command configdoc generates the environment-variable reference from config.Config.
package main

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/rknightion/cf2otel/internal/config"
)

func main() {
	fmt.Println("<!-- Generated by go run ./internal/configdoc; do not edit by hand. -->")
	fmt.Println("# Environment variables")
	fmt.Println()
	fmt.Println("Configuration loads defaults, then YAML, then `CF2OTEL_` environment overrides. Two underscores cross a YAML nesting boundary. Secrets must be supplied only through environment variables.")
	fmt.Println()
	fmt.Println("| YAML key | Environment variable |")
	fmt.Println("| --- | --- |")
	writeFields(reflect.TypeOf(config.Config{}), nil)
	fmt.Println()
	fmt.Println("The `collectors` map uses collector names such as `access.logins`; set its per-collector settings in YAML. The `otlp.headers` map contains secret values, so set each header through an environment variable, for example `CF2OTEL_OTLP__HEADERS__AUTHORIZATION`.")
	fmt.Println()
	fmt.Println("Required secret variables are `CF2OTEL_CLOUDFLARE__API_TOKEN` and `CF2OTEL_OTLP__GRAFANA_CLOUD__TOKEN`. The Grafana Cloud instance ID is `CF2OTEL_OTLP__GRAFANA_CLOUD__INSTANCE_ID`.")
}

func writeFields(t reflect.Type, path []string) {
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		key := strings.Split(field.Tag.Get("yaml"), ",")[0]
		if key == "" || key == "-" {
			continue
		}
		parts := append(append([]string{}, path...), key)
		if field.Type.Kind() == reflect.Struct && field.Type != reflect.TypeOf(config.Secret("")) {
			writeFields(field.Type, parts)
			continue
		}
		if field.Type.Kind() == reflect.Map {
			continue
		}
		fmt.Printf("| `%s` | `CF2OTEL_%s` |\n", strings.Join(parts, "."), strings.ToUpper(strings.Join(parts, "__")))
	}
}
