{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf2otel.serviceAccountName" . }}
  labels:
    {{- include "cf2otel.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
