package semconv

const (
	MetricHTTPVisits                    = "cloudflare.http.visits"
	MetricHTTPThreats                   = "cloudflare.http.threats"
	MetricHTTPAccountTransferMTD        = "cloudflare.http.account.transfer.month_to_date"
	MetricHTTPAccountTransferProjection = "cloudflare.http.account.transfer.projected_month_total"
	MetricHTTPResponseBytes             = "cloudflare.http.response.bytes"
	MetricHTTPEdgeTTFB                  = "cloudflare.http.edge.ttfb"
	MetricHTTPOriginResponseTime        = "cloudflare.http.origin.response_time"
	MetricHTTPRequestsByStatus          = "cloudflare.http.requests.by_status"
	MetricHTTPRequestsByCountry         = "cloudflare.http.requests.by_country"
	MetricHTTPRequestsByProtocol        = "cloudflare.http.requests.by_protocol"
	MetricHTTPRequestsByMethod          = "cloudflare.http.requests.by_method"
	MetricHTTPRequestsByContentType     = "cloudflare.http.requests.by_content_type"
	MetricHTTPResponseBytesByCountry    = "cloudflare.http.response.bytes.by_country"
	AttrHTTPClientCountry               = "cloudflare.http.client.country"
	AttrHTTPProtocol                    = "cloudflare.http.protocol"
	AttrHTTPTLSProtocol                 = "cloudflare.http.tls.protocol"
	AttrHTTPContentType                 = "cloudflare.http.content_type"

	EventHTTPRequest         = "cloudflare.http.request"
	MetricHTTPRequests       = "cloudflare.http.requests"
	MetricHTTPOriginDuration = "cloudflare.http.origin.duration"
	AttrHTTPHost             = "cloudflare.http.host"
	AttrHTTPMethod           = "cloudflare.http.method"
	AttrHTTPPath             = "cloudflare.http.path"
	AttrHTTPQuery            = "cloudflare.http.query"
	AttrHTTPStatusCode       = "cloudflare.http.status_code"
	AttrHTTPOriginStatusCode = "cloudflare.http.origin_status_code"
	AttrHTTPClientIP         = "cloudflare.http.client_ip"
	AttrHTTPUserAgent        = "cloudflare.http.user_agent"
	AttrHTTPRayID            = "cloudflare.http.ray_id"
	AttrHTTPZone             = "cloudflare.http.zone"
	AttrHTTPCacheStatus      = "cloudflare.http.cache_status"
	AttrHTTPSecurityAction   = "cloudflare.http.security_action"
	AttrHTTPColo             = "cloudflare.http.colo"
)
