package semconv

// MetricSpec holds instrument metadata for a declared metric.
type MetricSpec struct {
	Unit        string
	Description string
	Boundaries  []float64
}

// The operation buckets resolve latency through a minute; poller buckets also
// resolve short Cloudflare API calls and collector scrapes.
var genAIOperationDurationBuckets = []float64{0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 30, 60}
var pollerDurationBuckets = []float64{0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 7.5, 10, 15, 20, 30, 45, 60, 90, 120}

var metricSpecs = map[string]MetricSpec{
	MetricLBPoolHealth:                     {Unit: "1", Description: "Unattributed provider-reported health flag: true=1, false=0, unknown omitted; not regional aggregate pool availability. Other is the minimum of known flags, not complete fleet coverage."},
	MetricDEXHTTPFetchTime:                 {Unit: "ms", Description: "Provider requested-interval average HTTP resource fetch time; other is the arithmetic mean of per-test averages."},
	MetricDEXTracerouteRTT:                 {Unit: "ms", Description: "Provider requested-interval average traceroute round-trip time; other is the arithmetic mean of per-test averages."},
	MetricDEXTracerouteHops:                {Unit: "{hop}", Description: "Provider requested-interval average traceroute hop count; other is the arithmetic mean of per-test averages."},
	MetricDEXPacketLoss:                    {Unit: "%", Description: "Provider requested-interval average traceroute packet loss percentage; other is the arithmetic mean of per-test averages."},
	MetricDEXAvailability:                  {Unit: "%", Description: "Provider requested-interval average availability by test kind; other is the arithmetic mean of per-test averages."},
	MetricWorkersAIInferences:              {Unit: "1", Description: "Total number of inferences for an account from complete five-minute Groups buckets."},
	MetricWorkersAIInputTokens:             {Unit: "{token}", Description: "Total input tokens for an account from complete five-minute Groups buckets."},
	MetricWorkersAIOutputTokens:            {Unit: "{token}", Description: "Total output tokens for an account from complete five-minute Groups buckets."},
	MetricWorkersAIInferenceTime:           {Unit: "s", Description: "Total inference time for an account, converted from milliseconds."},
	MetricWARPDevices:                      {Unit: "1", Description: "Unique recently seen WARP devices by observed network status, platform, client version, mode and colo; bounded remainder preserves the total, without device/user identity."},
	MetricLogpushFailedUploads:             {Unit: "{upload}", Description: "Failed upload count by account/zone scope, zone name, job ID, destination type, status code and final attempt; explicit high-cardinality opt-in."},
	MetricHTTPVisits:                       {Unit: "{visit}", Description: "Additive visit sum by zone from adaptive Groups, following the configured request-source policy."},
	MetricHTTPThreats:                      {Unit: "{request}", Description: "Threat sum by zone from complete UTC-hour rollups held back at least ten minutes; not assumed eyeball-filterable."},
	MetricHTTPAccountTransferMTD:           {Unit: "By", Description: "UTC month-to-date eyeball response bytes, account aggregate without account ID or host."},
	MetricHTTPAccountTransferProjection:    {Unit: "By", Description: "Month-to-date bytes times UTC month seconds divided by elapsed complete-period seconds; zero for a zero-length period."},
	MetricDurableObjectsErrors:             {Unit: "{error}", Description: "Durable Objects invocation errors by bounded Workers script name."},
	MetricDurableObjectsWallTime:           {Unit: "s", Description: "Latest complete five-minute script bucket wall-time quantiles (p50, p75, p99, p999), converted from microseconds."},
	MetricDurableObjectsResponseSize:       {Unit: "By", Description: "Latest complete five-minute script bucket responseBodySize quantiles (p50, p75, p99, p999), in bytes."},
	MetricD1RowsRead:                       {Unit: "{row}", Description: "D1 rows read, account aggregate without database ID."},
	MetricD1RowsWritten:                    {Unit: "{row}", Description: "D1 rows written, account aggregate without database ID."},
	MetricD1QueryBatchTime:                 {Unit: "s", Description: "Latest complete account bucket queryBatchTimeMs quantiles (p50, p75, p99, p999), converted from milliseconds."},
	MetricD1QueryBatchResponseSize:         {Unit: "By", Description: "Latest complete account bucket queryBatchResponseBytes quantiles (p50, p75, p99, p999), in bytes."},
	MetricQueuesMessageLag:                 {Unit: "s", Description: "Latest observed complete bucket maximum of per-queue average ReadMessage lag, converted from milliseconds; no queue ID."},
	MetricQueuesMessageRetries:             {Unit: "{retry}", Description: "Latest observed complete bucket maximum of per-queue average ReadMessage retries; no queue ID."},
	MetricQueuesBillableOperationsByAction: {Unit: "{operation}", Description: "Billable operation sum by action type, consumer type and outcome; no queue ID; existing aggregate unchanged."},
	MetricHealthCheckEvents:                {Unit: "{event}", Description: "Health-check event count by zone name, source health-status string and bounded failure reason; Pro-only opt-in."},
	MetricHealthCheckRTT:                   {Unit: "s", Description: "Latest complete per-origin bucket average rttMs, converted from milliseconds; bounded non-IP origin identity."},
	MetricHealthCheckTTFB:                  {Unit: "s", Description: "Latest complete per-origin bucket average timeToFirstByteMs, converted from milliseconds; bounded non-IP origin identity."},
	MetricHealthCheckTCPConnection:         {Unit: "s", Description: "Latest complete per-origin bucket average tcpConnMs, converted from milliseconds; bounded non-IP origin identity."},
	MetricHealthCheckTLSHandshake:          {Unit: "s", Description: "Latest complete per-origin bucket average tlsHandshakeMs, converted from milliseconds; bounded non-IP origin identity."},
	MetricHTTPResponseBytes:                {Unit: "By", Description: "Response byte count on the HTTP request dimensions."},
	MetricHTTPEdgeTTFB:                     {Unit: "s", Description: "Edge time to first byte by zone, host and statistic (avg, p50, p95, p99); Pro only."},
	MetricHTTPOriginResponseTime:           {Unit: "s", Description: "Origin response time by zone, host and statistic (p50, p95, p99)."},
	MetricHTTPRequestsByColo:               {Unit: "{request}", Description: "Opt-in request count by zone and colo; bounded with a remainder."},
	MetricHTTPRequestsByASN:                {Unit: "{request}", Description: "Opt-in request count by zone, ASN and description; eligible zones only, bounded with a remainder."},
	MetricHTTPErrorsByRoute:                {Unit: "{request}", Description: "Opt-in error count by zone, configured safe route name and status class; never a path label."},
	MetricHTTPRequestsByStatus:             {Unit: "{request}", Description: "Request count by enabled edge and origin status. Zone-level, without host."},
	MetricHTTPRequestsByCountry:            {Unit: "{request}", Description: "Request count by client country. Zone-level, without host."},
	MetricHTTPRequestsByProtocol:           {Unit: "{request}", Description: "Request count by enabled HTTP and TLS protocol. Zone-level, without host."},
	MetricHTTPRequestsByMethod:             {Unit: "{request}", Description: "Request count by HTTP method. Zone-level, without host."},
	MetricHTTPRequestsByContentType:        {Unit: "{request}", Description: "Request count by response content type. Zone-level, without host."},
	MetricHTTPResponseBytesByCountry:       {Unit: "By", Description: "Response byte count by zone and client country, without host."},
	MetricWorkersInvocations:               {Unit: "{request}", Description: "Invocation count by script name and status."},
	MetricWorkersErrors:                    {Unit: "{error}", Description: "Invocation error count by script name."},
	MetricWorkersSubrequests:               {Unit: "{request}", Description: "Subrequest count by script name."},
	MetricWorkersCPUTime:                   {Unit: "s", Description: "CPU time by script name and statistic (p50, p75, p99, p999)."},
	MetricWorkersWallTime:                  {Unit: "s", Description: "Wall time by script name and statistic (p50, p75, p99, p999)."},
	MetricWorkersRequestDuration:           {Unit: "s", Description: "Request duration by script name and statistic (p50, p75, p99, p999)."},
	MetricCertificatePack:                  {Unit: "{pack}", Description: "Present certificate packs, including packs with unknown expiry."},
	MetricCertificateExpiry:                {Unit: "s", Description: "Seconds until the earliest certificate expiry in a pack; negative once expired."},
	MetricTunnelStatus:                     {Unit: "{tunnel}", Description: "Current tunnel status gauge with value 1, by id, name and status."},
	MetricTunnelConnections:                {Unit: "{connection}", Description: "Active tunnel connections by id, name and colo."},
	MetricTunnelConnectors:                 {Unit: "{connector}", Description: "Tunnel connectors by id, name and connector version."},
	MetricCardinalityOverflows:             {Unit: "{datapoint}", Description: "Overflow datapoint count by instrument."},
	MetricIdentityOutcomes:                 {Unit: "{request}", Description: "Identity inference outcome count by matched, unmatched or ambiguous outcome."},

	MetricWindowGap:                      {Unit: "s", Description: "Skipped retention-gap seconds by collector."},
	MetricAccessLogins:                   {Unit: "1", Description: "Human Access login count from cf1AccessLoginsRawGroups."},
	MetricAccessIdentityLogins:           {Unit: "1", Description: "Exact REST identity-login count by app, allowed, connection and action; excludes nonidentity service-token rows."},
	MetricAccessRequests:                 {Unit: "{request}", Description: "Access request count from accessLoginRequestsAdaptiveGroups; keep nonidentity traffic separate."},
	MetricAccessApps:                     {Unit: "1", Description: "Access application inventory gauge."},
	MetricAccessUsers:                    {Unit: "1", Description: "Access user inventory gauge."},
	MetricAccessSeats:                    {Unit: "1", Description: "Current user seat count by independent Access or Gateway flag; types overlap and must not be summed as unique billing users."},
	MetricHTTPRequests:                   {Unit: "{request}", Description: "Request count from sample-corrected httpRequestsAdaptiveGroups."},
	MetricHTTPOriginDuration:             {Unit: "s", Description: "Average origin response duration per Groups window, in seconds."},
	MetricAuditEvents:                    {Unit: "1", Description: "Exact audit event count by resource product, action type and action result."},
	MetricFirewallEvents:                 {Unit: "{event}", Description: "Security event count from a Groups dataset by zone and available dimensions, including advertised exporter-defined numeric bot score intervals and bounded score source names; all enrichment is bounded by the collector's total per-window series cap."},
	MetricDNSQueries:                     {Unit: "1", Description: "DNS query count from dnsAnalyticsAdaptiveGroups by zone and available bounded dimensions."},
	MetricGatewayDNSQueries:              {Unit: "1", Description: "Gateway DNS query sum from account-level cf1GatewayDnsRawGroups, by bounded query type, resolver decision and country."},
	MetricRUMPageViews:                   {Unit: "1", Description: "Page views from rumPageloadEventsAdaptiveGroups by country and device."},
	MetricRUMSessions:                    {Unit: "1", Description: "Visit sum from rumPageloadEventsAdaptiveGroups by country and device."},
	MetricRUMLCPP75:                      {Unit: "s", Description: "Rolling p75 largest contentful paint in seconds, converted from GraphQL milliseconds."},
	MetricRUMINPP75:                      {Unit: "s", Description: "Rolling p75 interaction to next paint in seconds, converted from GraphQL milliseconds."},
	MetricRUMFIDP75:                      {Unit: "s", Description: "Rolling p75 first input delay in seconds, converted from GraphQL milliseconds."},
	MetricRUMFCPP75:                      {Unit: "s", Description: "Rolling p75 first contentful paint in seconds, converted from GraphQL milliseconds."},
	MetricRUMTTFBP75:                     {Unit: "s", Description: "Rolling p75 time to first byte in seconds, converted from GraphQL milliseconds."},
	MetricRUMCLSP75:                      {Unit: "1", Description: "Rolling p75 cumulative layout shift score gauge."},
	MetricWorkersRequests:                {Unit: "{request}", Description: "Worker request count from workersOverviewRequestsAdaptiveGroups, optionally by bounded script name."},
	MetricTurnstileEvents:                {Unit: "1", Description: "Turnstile event count from turnstileAdaptiveGroups, account aggregate."},
	MetricLogpushUploads:                 {Unit: "1", Description: "Logpush upload count from logpushHealthAdaptiveGroups, account aggregate."},
	MetricLogpushRecords:                 {Unit: "1", Description: "Logpush record count from logpushHealthAdaptiveGroups, account aggregate."},
	MetricD1ReadQueries:                  {Unit: "1", Description: "D1 read query sum from d1AnalyticsAdaptiveGroups by bounded resolved database name."},
	MetricD1WriteQueries:                 {Unit: "1", Description: "D1 write query sum from d1AnalyticsAdaptiveGroups by bounded resolved database name."},
	MetricD1Queries:                      {Unit: "1", Description: "D1 query count by bounded resolved database name; query text is not selected."},
	MetricD1StorageBytes:                 {Unit: "By", Description: "Maximum D1 database size by bounded resolved database name in the latest global complete bucket, By."},
	MetricKVRequests:                     {Unit: "{request}", Description: "KV operation request sum by bounded resolved namespace name."},
	MetricKVStorageBytes:                 {Unit: "By", Description: "Maximum KV namespace bytes by bounded resolved namespace name in the latest global complete bucket, By."},
	MetricKVStorageKeys:                  {Unit: "{key}", Description: "Maximum KV namespace key count by bounded resolved namespace name in the latest global complete bucket."},
	MetricR2BandwidthDownloadBytes:       {Unit: "By", Description: "R2 download byte sum, optionally by bounded bucket name, By."},
	MetricR2BandwidthUploadBytes:         {Unit: "By", Description: "R2 upload byte sum, optionally by bounded bucket name, By."},
	MetricR2CatalogDataOperations:        {Unit: "1", Description: "R2 catalog data operation count, optionally by bounded namespace name."},
	MetricR2CatalogMaintenanceJobs:       {Unit: "1", Description: "R2 catalog maintenance job count, optionally by bounded namespace name."},
	MetricR2Requests:                     {Unit: "{request}", Description: "R2 operation request sum by advertised action type and optional bucket name, capped by complete attribute set."},
	MetricR2StoragePayloadBytes:          {Unit: "By", Description: "R2 payload-size gauge in the latest complete bucket per bucket, By."},
	MetricR2StorageObjects:               {Unit: "{object}", Description: "R2 object-count gauge in the latest complete bucket per bucket."},
	MetricR2SQLQueries:                   {Unit: "1", Description: "R2 SQL query count, optionally by bounded bucket name; table names are omitted."},
	MetricDurableObjectsRequests:         {Unit: "{request}", Description: "Durable Objects invocation request sum by bounded resolved namespace name."},
	MetricDurableObjectsSubrequests:      {Unit: "{request}", Description: "Durable Objects periodic subrequest sum by bounded resolved namespace name."},
	MetricDurableObjectsSQLStorageBytes:  {Unit: "By", Description: "Maximum Durable Objects SQL storage by bounded resolved namespace name in the latest global complete bucket, By."},
	MetricDurableObjectsRequestBodyBytes: {Unit: "By", Description: "Durable Objects uncached request-body byte sum by bounded resolved namespace name, By."},
	MetricQueuesBacklogMessages:          {Unit: "{message}", Description: "Maximum per-queue average backlog messages by bounded resolved queue name in the latest global complete bucket."},
	MetricQueuesBacklogBytes:             {Unit: "By", Description: "Maximum per-queue average backlog bytes by bounded resolved queue name in the latest global complete bucket, By."},
	MetricQueuesConsumerConcurrency:      {Unit: "{consumer}", Description: "Maximum per-queue average consumer concurrency by bounded resolved queue name in the latest global complete bucket."},
	MetricQueuesDelayedBacklogMessages:   {Unit: "{message}", Description: "Maximum per-queue average delayed backlog messages by bounded resolved queue name in the latest global complete bucket."},
	MetricQueuesMessageOperations:        {Unit: "1", Description: "Queue message operation count by bounded resolved queue name."},
	MetricQueuesBillableOperations:       {Unit: "1", Description: "Queue billable operation sum by bounded resolved queue name."},
	MetricAIGatewayRequests:              {Unit: "{request}", Description: "AI Gateway request count."},
	MetricAIGatewayBodyNonJSON:           {Unit: "{request}", Description: "AI Gateway non-JSON bodies omitted from content export, by request or response side."},
	MetricAIGatewayErrors:                {Unit: "1", Description: "AI Gateway error count."},
	MetricAIGatewayCacheHits:             {Unit: "1", Description: "AI Gateway cache hits."},
	MetricAIGatewayCost:                  {Unit: "1", Description: "AI Gateway request cost."},
	MetricAIGatewayDLPRequests:           {Unit: "{request}", Description: "AI Gateway request count with a DLP outcome, by gateway, action and direction."},
	MetricAIGatewayLogCoverageGap:        {Unit: "{request}", Description: "GraphQL Groups request count minus REST log count for one closed five-minute window, by gateway; a completeness check, not a request rate."},
	MetricGenAIDuration:                  {Unit: "s", Description: "GenAI operation duration.", Boundaries: genAIOperationDurationBuckets},
	MetricGenAIInputTokens:               {Unit: "{token}", Description: "Input token usage."},
	MetricGenAIOutputTokens:              {Unit: "{token}", Description: "Output token usage."},
	MetricGenAICacheReadTokens:           {Unit: "{token}", Description: "Cached input tokens."},
	MetricGenAIReasoningTokens:           {Unit: "{token}", Description: "Reasoning output tokens."},
	MetricGenAIInputOperationTokens:      {Unit: "{token}", Description: "Input tokens by operation."},
	MetricGenAIOutputOperationTokens:     {Unit: "{token}", Description: "Output tokens by operation."},
	MetricScrapeSuccess:                  {Unit: "1", Description: "Collector scrape success state."},
	MetricZonesDiscovered:                {Unit: "{zone}", Description: "Zones returned by discovery for a complete collector poll."},
	MetricZonesFiltered:                  {Unit: "{zone}", Description: "Zones removed by include, ownership or exclusion selection, by reason."},
	MetricZonesProcessed:                 {Unit: "{zone}", Description: "Distinct eligible zones queried in a complete collector poll."},
	MetricZonesSkipped:                   {Unit: "{zone}", Description: "Eligible zones not queried in a complete collector poll, by reason."},
	MetricScrapeDuration:                 {Unit: "s", Description: "Collector scrape duration.", Boundaries: pollerDurationBuckets},
	MetricScrapeErrors:                   {Unit: "1", Description: "Collector scrape errors."},
	MetricScrapeLastSuccess:              {Unit: "s", Description: "Time of last successful collector scrape."},
	MetricExportSuccess:                  {Unit: "1", Description: "Successful OTLP exports."},
	MetricExportErrors:                   {Unit: "1", Description: "Failed OTLP exports."},
	MetricBuildInfo:                      {Unit: "1", Description: "Build identity."},
	MetricCheckpointAge:                  {Unit: "s", Description: "Age of the oldest collector checkpoint."},
	MetricAPIRequests:                    {Unit: "{request}", Description: "Physical Cloudflare HTTP requests by collector, REST/GraphQL method and failure-only error class."},
	MetricAPIEnvelopeErrors:              {Unit: "{error}", Description: "Unsuccessful Cloudflare API envelopes returned with successful HTTP status."},
	MetricAPIDuration:                    {Unit: "s", Description: "Physical Cloudflare HTTP request duration through response headers, excluding limiter wait, by collector and REST/GraphQL method.", Boundaries: pollerDurationBuckets},
	MetricAPILimiterWait:                 {Unit: "s", Description: "Process limiter acquisition time for each physical Cloudflare HTTP request, by collector and REST/GraphQL method.", Boundaries: pollerDurationBuckets},
	MetricAPIRetries:                     {Unit: "1", Description: "Cloudflare API retries."},
	MetricWindowCommitFailures:           {Unit: "1", Description: "Failed window commits by retry or dropped outcome."},
	MetricWindowCatchupWindows:           {Unit: "1", Description: "Additional bounded collector windows committed in one scheduler tick."},
	MetricEmailRoutingEvents:             {Unit: "1", Description: "Email Routing event count."},
	MetricEmailSendingEvents:             {Unit: "1", Description: "Email Sending event count."},
	MetricHTTPLatencyHostVariants:        {Unit: "{group}", Description: "Discarded HTTP latency source groups normalizing to an existing host, by zone; only the largest-count group's timings are exported."},
}

// Metric returns metadata for a metric declared by this package.
func Metric(name string) (MetricSpec, bool) {
	spec, ok := metricSpecs[name]
	return spec, ok
}
