package semconv

const (
	MetricWorkersRequests                = "cloudflare.workers.requests"
	MetricTurnstileEvents                = "cloudflare.turnstile.events"
	MetricLogpushUploads                 = "cloudflare.logpush.uploads"
	MetricLogpushRecords                 = "cloudflare.logpush.records"
	MetricD1ReadQueries                  = "cloudflare.d1.read_queries"
	MetricD1WriteQueries                 = "cloudflare.d1.write_queries"
	MetricD1Queries                      = "cloudflare.d1.queries"
	MetricD1StorageBytes                 = "cloudflare.d1.storage.max_database_bytes"
	MetricKVRequests                     = "cloudflare.kv.requests"
	MetricKVStorageBytes                 = "cloudflare.kv.storage.max_namespace_bytes"
	MetricKVStorageKeys                  = "cloudflare.kv.storage.max_namespace_keys"
	MetricR2BandwidthDownloadBytes       = "cloudflare.r2.bandwidth.download.bytes"
	MetricR2BandwidthUploadBytes         = "cloudflare.r2.bandwidth.upload.bytes"
	MetricR2CatalogDataOperations        = "cloudflare.r2.catalog.data.operations"
	MetricR2CatalogMaintenanceJobs       = "cloudflare.r2.catalog.maintenance.jobs"
	MetricR2Requests                     = "cloudflare.r2.requests"
	MetricR2StoragePayloadBytes          = "cloudflare.r2.storage.payload.bytes"
	MetricR2StorageObjects               = "cloudflare.r2.storage.objects"
	MetricR2SQLQueries                   = "cloudflare.r2sql.queries"
	MetricDurableObjectsRequests         = "cloudflare.durableobjects.requests"
	MetricDurableObjectsSubrequests      = "cloudflare.durableobjects.subrequests"
	MetricDurableObjectsSQLStorageBytes  = "cloudflare.durableobjects.sql_storage.max_namespace_bytes"
	MetricDurableObjectsRequestBodyBytes = "cloudflare.durableobjects.subrequests.request_body.bytes"
	MetricQueuesBacklogMessages          = "cloudflare.queues.backlog.max_queue_avg_messages"
	MetricQueuesBacklogBytes             = "cloudflare.queues.backlog.max_queue_avg_bytes"
	MetricQueuesConsumerConcurrency      = "cloudflare.queues.consumer.max_queue_avg_concurrency"
	MetricQueuesDelayedBacklogMessages   = "cloudflare.queues.delayed_backlog.max_queue_avg_messages"
	MetricQueuesMessageOperations        = "cloudflare.queues.message.operations"
	MetricQueuesBillableOperations       = "cloudflare.queues.message.billable_operations"

	AttrWorkersScriptName      = "cloudflare.workers.script_name"
	AttrR2BucketName           = "cloudflare.r2.bucket_name"
	AttrR2CatalogNamespaceName = "cloudflare.r2.catalog.namespace_name"
	AttrR2SQLBucketName        = "cloudflare.r2sql.bucket_name"
)
