package semconv

const (
	MetricScrapeSuccess     = "cf2otel.scrape.success"
	MetricScrapeDuration    = "cf2otel.scrape.duration"
	MetricScrapeErrors      = "cf2otel.scrape.errors"
	MetricScrapeLastSuccess = "cf2otel.scrape.last_success_timestamp"
	MetricExportSuccess     = "cf2otel.export.success"
	MetricExportErrors      = "cf2otel.export.errors"
	MetricBuildInfo         = "cf2otel.build.info"
	AttrCollector           = "cf2otel.collector"
	AttrVersion             = "cf2otel.version"
	AttrCommit              = "cf2otel.commit"
	AttrExportSignal        = "cf2otel.export.signal"
	AttrBuildVersion        = "cf2otel.build.version"
	AttrBuildCommit         = "cf2otel.build.commit"
	MetricCheckpointAge     = "cf2otel.checkpoint.age"
	MetricAPIRequests       = "cf2otel.api.requests"
	MetricAPIDuration       = "cf2otel.api.duration"
	MetricAPIRetries        = "cf2otel.api.retries"
	SpanAPIRequest          = "cf2otel.api.request"
	AttrAPIMethod           = "cf2otel.api.method"
	MetricIdentityMatched   = "cf2otel.identity.matched"
	MetricIdentityUnmatched = "cf2otel.identity.unmatched"
	MetricIdentityAmbiguous = "cf2otel.identity.ambiguous"
)
