name: Helm
on:
  push:
    branches: [main]
    paths:
      - "charts/**"
      - ".github/workflows/helm.yml"
  pull_request:
permissions:
  contents: read
concurrency:
  group: helm-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/helm-validate.yml@e17f6f1a010f50cf878b310cf90820f14c0bbbf6 # v1.25.2
    with:
      chart-path: charts/cf2otel
      kubernetes-versions: "1.29.0"
      schema-locations: >-
        default
        https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
