name: Helm
on:
  push:
    branches: [main]
    paths:
      - "charts/**"
      - ".github/workflows/helm.yml"
  pull_request:
permissions:
  contents: read
concurrency:
  group: helm-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/helm-validate.yml@8d14adaa295c4a7670b1d4e744b070955b710598 # v1.24.0
    with:
      chart-path: charts/cf2otel
      kubernetes-versions: "1.29.0"
      schema-locations: >-
        default
        https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
